### ISSUE TITLE
Merge script not moving renamed files?

### ISSUE THREAD

**Issue by Mathadon** [ibpsa/modelica-ibpsa#138]
We now have separate packages for `Examples` and `Validations`. Since some examples were moved from one package to the other some files were renamed in git. However the merge script does not take this into account and it copies the new files (and their .mos files) to the new location without removing the old files. Consequently I now have two times the same model and unit test, resulting in an error when running the unit test script:

```
ValueError: *** Error: Result file ConstantEffectivenessHex.mat is generated by more than one script.
           You need to make sure that all scripts use unique result file names.
```

A possible solution is to create an index of all copied files in the remote package when doing the merge. During next merge these files can then first be removed before copying new files.

**Comment by Mathadon** [comment]
I tried to merge again and there still seem to be issues caused by files not being removed. During latest merge not a single file was removed, leading to duplicate declarations of /Water and Water.mo, etc.
I am using buildingspy version 55527faf91eb931dc43fbf548d124add64922fa5

**Comment by Mathadon** [comment]
It is caused by the following line of code:
```
roo = self._target_home.split(self._new_library_name)[0]
```
my path is:
```
/Users/werk/Documents/Software/IDEAS-git/IDEAS
```
but ```roo``` returns ```/Users/werk/Documents/Software```.

I'm not sure what your intention was with that line of code but another solution may be:
```
roo = os.path.join(self._target_home, "../")
```
this does work for me.

**Comment by mwetter** [comment]
How does your merge script look like? Is it like 
```
import buildingspy.development.merger as m
import os
annex60_dir = "/home/mwetter/proj/ldrd/bie/modeling/github/iea-annex60/modelica-annex60/Annex60"
dest_dir = "/home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings"
mer = m.Annex60(annex60_dir, dest_dir)
mer.merge()

```
This script works for me from different directories. To produce the output below, I added
```
            print "self._target_home.split = {}".format(self._target_home)
            print "self._new_library_name = {}".format(self._new_library_name)
            print "roo = {}".format(roo)
```

in merger.py, line 159
```
mwetter@srg-mw:~/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings$ python mergeAnnex60.py 
self._target_home.split = /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings
self._new_library_name = Buildings
roo = /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/
mwetter@srg-mw:~/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings$ cd Buildings/
mwetter@srg-mw:~/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings$ python ../mergeAnnex60.py 
self._target_home.split = /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/Buildings
self._new_library_name = Buildings
roo = /home/mwetter/proj/ldrd/bie/modeling/github/lbl-srg/modelica-buildings/
```

**Comment by Mathadon** [comment]
The problem is that my full IDEAS path is:
```
/Users/werk/Documents/Software/IDEAS-git/IDEAS
```
which contains 'IDEAS' twice. Python detects the first IDEAS and uses this to set up the path, while it should use the second. 
My merger script is:
```
import buildingspy.development.merger as m
import os
import io,json

fileName = "Scripts/mergePaths.txt"
if os.path.isfile(fileName):
    with open(fileName, 'r') as dataFile:
        data = json.loads(dataFile.read())
        annex60_dir = data['annex60_dir']
        dest_dir = data['dest_dir']
        
else:
    print fileName + " could not be found in your current working directory, please enter source and destination paths. \nThey will be saved for next time. Remove " + fileName + " to reset the paths." 
    annex60_dir = raw_input("Enter annex60 directory path: \n")
    dest_dir = raw_input("Enter destination directory path: \n")
    data = {"annex60_dir":annex60_dir, "dest_dir":dest_dir}
    with open(fileName, 'w') as dataFile:
        json.dump(data, dataFile)

mer = m.Annex60(annex60_dir, dest_dir) 
mer.set_excluded_packages(["Experimental", "Obsolete"])
mer.merge()
```

**Comment by mwetter** [comment]
@Mathadon : can you try again with the master from https://github.com/lbl-srg/BuildingsPy.
The commit https://github.com/lbl-srg/BuildingsPy/commit/4d7887a89368afcdef7557c3c107ab0b376f755d
should fix this.

**Comment by Mathadon** [comment]
It looks like it's fixed, thanks!

**Comment by Mathadon** [comment]
Oops, I was using the wrong version. I now get a new error:
```
Traceback (most recent call last):
  File "Scripts/mergeAnnex60Script.py", line 23, in <module>
    mer.merge()
  File "/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/merger.py", line 231, in merge
    r.write_package_order(self._target_home, True)
  File "/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/refactor.py", line 390, in write_package_order
    write_package_order(directory=ele, recursive=False)
  File "/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg/buildingspy/development/refactor.py", line 405, in write_package_order
    if recordString in fil.readline():
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by mwetter** [comment]
Can you try with BuildingsPy from the master on https://github.com/lbl-srg/BuildingsPy ?
You seem to be using an old release: `/Library/Python/2.7/site-packages/buildingspy-1.4.0-py2.7.egg`

**Comment by Mathadon** [comment]
I think that's what I did:
```
macbookprofj:BuildingsPy werk$ git pull origin master
From github.com:lbl-srg/BuildingsPy
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```
I reran setup.py but I still get the same error.

**Comment by mwetter** [comment]
Are you sure that `BuildingsPy` from the master is executed? Try
```bash
export PYTHONPATH=xxx 
```
where `xxx` points to `BuildingsPy`. You can also try to add a print statement to the merge function to make sure you execute the version you think you do.

For me, merging to IDEAS works:
```bash
mbp:IDEAS mwetter$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	mergeAnnex60.py

nothing added to commit but untracked files present (use "git add" to track)
mbp:IDEAS mwetter$ git pull
Already up-to-date.
mbp:IDEAS mwetter$ cat mergeAnnex60.py
import buildingspy.development.merger as m
import os
import io,json

annex60_dir = "/Users/mwetter/proj/ldrd/bie/modeling/github/iea-annex60/modelica-annex60/Annex60"
dest_dir = "/Users/mwetter/proj/ldrd/bie/modeling/github/IDEAS/IDEAS"

mer = m.Annex60(annex60_dir, dest_dir) 
mer.set_excluded_packages(["Experimental", "Obsolete"])
mer.merge()
mbp:IDEAS mwetter$ python mergeAnnex60.py
mbp:IDEAS mwetter$ git status | head -n 10
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   IDEAS/BoundaryConditions/SkyTemperature/BlackBody.mo
	modified:   IDEAS/BoundaryConditions/SkyTemperature/Examples/BlackBody.mo
	modified:   IDEAS/BoundaryConditions/SkyTemperature/package.mo
	modified:   IDEAS/BoundaryConditions/SolarGeometry/BaseClasses/AltitudeAngle.mo
```

**Comment by Mathadon** [comment]
That did not work.

I debugged the code. The problem seems to be that at the start of the file ```IDEAS/Fluid/HeatExchangers/GroundHeatExchangers/Borefield/MultipleBoreHoles.mo``` there were some weird characters before the actual text. I added a newline before the original first line of the file:
```
within IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield;
```
and added/changed following lines in ```refactor.py```
```
                        if os.path.join(directory, f) == "/Users/werk/Documents/Software/IDEAS-git/IDEAS/Fluid/HeatExchangers/GroundHeatExchangers/Borefield/MultipleBoreHoles.mo":
                            print test
                            print [chr(ord(c)) for c in test]
                        if recordString in test:
                            typ = __REC
                            break;
```
this resulted in the following output:
```
[' \xef', '\xbb', '\xbf', '\n']

I copied the file text in a new file and saved that new file instead of the existing one and the problem was solved.
